name: Health Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nextjs:
        image: node:16
        options: --cpus 2
        ports:
          - 3000:3000
        volumes:
          - .:/home/node/app
        env:
          NODE_ENV: production
        run: |
          cd /home/node/app
          npm install
          npm run build
          npm start &
          sleep 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app
        run: |
          npm start &
          sleep 60

      - name: Run E2E tests
        run: npm run test:e2e
